In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [ ]:
temp = np.arange(1,21)
result = np.ones(20) * 2
(result**temp)/temp

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [ ]:
temp = np.ones(6)
temp_one = temp/10
temp_two = temp_one * 2
np.shares_memory(temp_one, temp_two)
i = np.arange(0,6) 
temp_one = temp_one ** (3 * i)
temp_two = temp_two ** (4 * i )
result = temp_one * temp_two
result.sum()

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [ ]:
matrix = np.zeros((8,8))
matrix[1::2,::2] = 1
matrix[::2,1::2] = 1
matrix

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [17]:
X = np.random.random((5, 2))
def cart_to_pol(points):
    rho = np.sqrt((points[:,0])**2 + (points[:,1])**2)
    phi = np.arctan2((points[:,1]), (points[:,0]))
    return rho, phi
cart_to_pol(X)

(array([1.153876  , 0.97969261, 0.67946043, 0.62715703, 0.52234674]),
 array([0.64781606, 1.19795062, 1.05885382, 0.96382331, 0.60832774]))

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [ ]:
X = np.random.random((10, 10))
x = np.argmax(X) // 10
y = np.argmax(X) - x * 10
print(x,y)
X >= X[x][y]


4 4


array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False,  True, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [ ]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))
d = X-y
d = d**2
distan = d[:,0] + d[:,1]
print(np.sqrt(distan))
np.argmin(distan)

[1.13420065 0.52101537 0.59604384 0.71128328 0.97565053 0.70022383
 0.53711188 0.90690939 0.55478816 0.20716055]


9

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [ ]:
x_l = np.linspace(-3,0,3,False)
y_l = x_l**2 + 2*x_l + 6
x_m = np.linspace(0,2,2,False)
y_m = x_m + 6
x_r = np.linspace(2,3,2)
y_r = x_r**2 + 4 * x_r - 4
np.hstack((y_l,y_m,y_r))



array([ 9.,  6.,  5.,  6.,  7.,  8., 17.])

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [12]:
X = np.random.random((10, 10))

median = np.mean(X,axis=1)
median.resize(10,1)
np.mean(X - median,axis=1)

array([ 5.55111512e-17,  4.44089210e-17,  2.22044605e-17,  1.11022302e-16,
        9.99200722e-17, -8.88178420e-17, -1.11022302e-17, -1.11022302e-17,
        6.66133815e-17, -4.44089210e-17])

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [16]:
X = np.random.normal(loc=5, scale=2., size=1000)
print("Выборочное среднее", np.average(X))
print("Выборочная дисперсия", np.var(X, ddof=1))


Выборочное среднее 5.0063064637490875
Выборочная дисперсия 4.18705403292446


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [18]:
X = np.arange(0,5,1)
X = np.append(X, [np.roll(X, -1),np.roll(X, -2), np.roll(X, -3), np.roll(X,-4)])
X.reshape((5,5))

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0],
       [2, 3, 4, 0, 1],
       [3, 4, 0, 1, 2],
       [4, 0, 1, 2, 3]])

**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [ ]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[0, 0, 4, 0, 0]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [25]:
def sample(x,c):
  s = np.cumsum(x)
  all_sum = np.sum(x)
  res = all_sum * np.random.random(c)
  argmax =  (res.reshape(-1,1) < s).argmax(axis=1)
  return argmax.tolist()


In [24]:
sample([50, 3, 1, 7, 20], 5)

[[ True  True  True  True  True]
 [False False  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [False False False False  True]]


[0, 2, 0, 0, 4]

False